( Dependencies: bootstrap.f, stdstring.f, stdassert.f, stdctx.f, stdexcept.f )

( <stdio.f> :; This file implements IO functions so users don't need to manually invoke syscalls. )

CLEAR WORD STDIO_M FIND ~ POPBUFXT EXEC_IF MACROS CREATE STDIO_M

( Since our exceptions don't reinvert errno values like libc does we use the negative constants )
-1 CONSTANT EPERM
-2 CONSTANT ENOENT
-3 CONSTANT ESRCH
-4 CONSTANT EINTR
-5 CONSTANT EIO
-6 CONSTANT ENXIO
-7 CONSTANT E2BIG
-8 CONSTANT ENOEXEC
-9 CONSTANT EBADF
-10 CONSTANT ECHILD
-11 CONSTANT EAGAIN
-12 CONSTANT ENOMEM
-13 CONSTANT EACCES
-14 CONSTANT EFAULT
-15 CONSTANT ENOTBLK
-16 CONSTANT EBUSY
-17 CONSTANT EEXIST
-18 CONSTANT EXDEV
-19 CONSTANT ENODEV
-20 CONSTANT ENOTDIR
-21 CONSTANT EISDIR
-22 CONSTANT EINVAL
-23 CONSTANT ENFILE
-24 CONSTANT EMFILE
-25 CONSTANT ENOTTY
-26 CONSTANT ETXTBSY
-27 CONSTANT EFBIG
-28 CONSTANT ENOSPC
-29 CONSTANT ESPIPE
-30 CONSTANT EROFS
-31 CONSTANT EMLINK
-32 CONSTANT EPIPE
-33 CONSTANT EDOM
-34 CONSTANT ERANGE
-35 CONSTANT EDEADLK
-36 CONSTANT ENAMETOOLONG
-37 CONSTANT ENOLCK
-38 CONSTANT ENOSYS
-39 CONSTANT ENOTEMPTY
-40 CONSTANT ELOOP
( no -41 )
-42 CONSTANT ENOMSG
-43 CONSTANT EIDRM
-44 CONSTANT ECHRNG
-45 CONSTANT EL2NSYNC
-46 CONSTANT EL3HLT
-47 CONSTANT EL3RST
-48 CONSTANT ELNRNG
-49 CONSTANT EUNATCH
-50 CONSTANT ENOCSI
-51 CONSTANT EL2HLT
-52 CONSTANT EBADE
-53 CONSTANT EBADR
-54 CONSTANT EXFULL
-55 CONSTANT ENOANO
-56 CONSTANT EBADRQC
-57 CONSTANT EBADSLT
( no -58 )
-59 CONSTANT EBFONT
-60 CONSTANT ENOSTR
-61 CONSTANT ENODATA
-62 CONSTANT ETIME
-63 CONSTANT ENOSR
-64 CONSTANT ENONET
-65 CONSTANT ENOPKG
-66 CONSTANT EREMOTE
-67 CONSTANT ENOLINK
-68 CONSTANT EADV
-69 CONSTANT ESRMNT
-70 CONSTANT ECOMM
-71 CONSTANT EPROTO
-72 CONSTANT EMULTIHOP
-73 CONSTANT EDOTDOT
-74 CONSTANT EBADMSG
-75 CONSTANT EOVERFLOW
-76 CONSTANT ENOTUNIQ
-77 CONSTANT EBADFD
-78 CONSTANT EREMCHG
-79 CONSTANT ELIBACC
-80 CONSTANT ELIBBAD
-81 CONSTANT ELIBSCN
-82 CONSTANT ELIBMAX
-83 CONSTANT ELIBEXEC
-84 CONSTANT EILSEQ
-85 CONSTANT ERESTART
-86 CONSTANT ESTRPIPE
-87 CONSTANT EUSERS
-88 CONSTANT ENOTSOCK
-89 CONSTANT EDESTADDRREQ
-90 CONSTANT EMSGSIZE
-91 CONSTANT EPROTOTYPE
-92 CONSTANT ENOPROTOOPT
-93 CONSTANT EPROTONOSUPPORT
-94 CONSTANT ESOCKTNOSUPPORT
-95 CONSTANT EOPNOTSUPP
-96 CONSTANT EPFNOSUPPORT
-97 CONSTANT EAFNOSUPPORT
-98 CONSTANT EADDRINUSE
-99 CONSTANT EADDRNOTAVAIL
-100 CONSTANT ENETDOWN
-101 CONSTANT ENETUNREACH
-102 CONSTANT ENETRESET
-103 CONSTANT ECONNABORTED
-104 CONSTANT ECONNRESET
-105 CONSTANT ENOBUFS
-106 CONSTANT EISCONN
-107 CONSTANT ENOTCONN
-108 CONSTANT ESHUTDOWN
-109 CONSTANT ETOOMANYREFS
-110 CONSTANT ETIMEDOUT
-111 CONSTANT ECONNREFUSED
-112 CONSTANT EHOSTDOWN
-113 CONSTANT EHOSTUNREACH
-114 CONSTANT EALREADY
-115 CONSTANT EINPROGRESS
-116 CONSTANT ESTALE
-117 CONSTANT EUCLEAN
-118 CONSTANT ENOTNAM
-119 CONSTANT ENAVAIL
-120 CONSTANT EISNAM
-121 CONSTANT EREMOTEIO
-122 CONSTANT EDQUOT
-123 CONSTANT ENOMEDIUM
-124 CONSTANT EMEDIUMTYPE
-125 CONSTANT ECANCELED
-126 CONSTANT ENOKEY
-127 CONSTANT EKEYEXPIRED
-128 CONSTANT EKEYREVOKED
-129 CONSTANT EKEYREJECTED
-130 CONSTANT EOWNERDEAD
-131 CONSTANT ENOTRECOVERABLE
-132 CONSTANT ERFKILL
-133 CONSTANT EHWPOISON

ENDMACROS

CLEAR WORD STDIO_F FIND ~ POPBUFXT EXEC_IF CREATE STDIO_F

( Helpers for invoking syscalls with set argument counts. )
: SYSCALL0 >C 0 DUP DUP DUP DUP DUP C> SYSCALL ;
: SYSCALL1 >C >C 0 DUP DUP DUP DUP C> C> SYSCALL ;
: SYSCALL2 >C >C >C 0 DUP DUP DUP C> C> C> SYSCALL ;
: SYSCALL3 >C >C >C >C 0 DUP DUP C> C> C> C> SYSCALL ;
: SYSCALL4 >C >C >C >C >C 0 DUP C> C> C> C> C> SYSCALL ;
: SYSCALL5 >C >C >C >C >C >C 0 C> C> C> C> C> C> SYSCALL ;

( Helpers for invoking syscalls with set argument counts and throwing on errors. )
: #SYSCALL SYSCALL DUP -? IF THROW THEN ;
: #SYSCALL0 >C 0 DUP DUP DUP DUP DUP C> #SYSCALL ;
: #SYSCALL1 >C >C 0 DUP DUP DUP DUP C> C> #SYSCALL ;
: #SYSCALL2 >C >C >C 0 DUP DUP DUP C> C> C> #SYSCALL ;
: #SYSCALL3 >C >C >C >C 0 DUP DUP C> C> C> C> #SYSCALL ;
: #SYSCALL4 >C >C >C >C >C 0 DUP C> C> C> C> C> #SYSCALL ;
: #SYSCALL5 >C >C >C >C >C >C 0 C> C> C> C> C> C> #SYSCALL ;

( Note; all following functions throw on errors rather than returning error values,
if you want to invoke a non-throwing syscall manually use one of the SYSCALLn wrappers,
and if you want to extend the library with new IO functions use one of the #SYSCALLn wrappers. )

1 CONSTANT STDOUT
0 CONSTANT STDIN

: READ 0 #SYSCALL3 ;
: WRITE 1 #SYSCALL3 ;
: OPENAT 257 #SYSCALL4 ;
( Instead of directly invoking sys_open since it's a bit old now
we just call sys_openat while specifying that the path is relative to the CWD. )
: OPEN -100 OPENAT ; 
: CLOSE 3 #SYSCALL1 ;

DWORD_T VARIABLE FDBUF ( for use in WRITE_FULL and READ_FULL, DWORD_T since on Linux file descriptors are 32 bits. )

( WRITE_FULL and READ_FULL respectively are wrappers around WRITE and READ that guarantee that all bytes requested where read/written on success.
They return nothing on success, and throw on failure. Note that a failure does not mean no IO was performed, it could also mean a partial read or write happened. )
: WRITE_FULL
    FDBUF !d BEGIN
    OVER WHILE
        2DUP FDBUF @d WRITE TUCK ( copy the val so our stack looks like [ count, written, buf, written ] )
        + -ROT SWAP - SWAP ( add the return value to the buffer and subtract it from the count to write )
    REPEAT
    2POP
;

: READ_FULL
    FDBUF !d BEGIN
    OVER WHILE
        2DUP FDBUF @d READ
        DUP IF ( if not EOF )
            TUCK + -ROT SWAP - SWAP
        ELSE
            ( throw EINVAL on a read that got EOF, as our function's contract makes a
            valid length argument be only one that never causes us to go past EOF )
            -22 THROW 
        THEN
    REPEAT
    2POP
;

21 VARIABLE NUMBUF
BYTE_T VARIABLE CHARBUF

: PRINT DUP STRLEN SWAP BASE + STDOUT WRITE_FULL ;
: PUTCHAR CHARBUF !b 1 CHARBUF BASE + STDOUT WRITE_FULL ;
: PUTLN 10 PUTCHAR ;
: PRINTLN PRINT PUTLN ;
: PRINTNUM [ NUMBUF 20 + ] LITERAL I64TS PRINT ;

( . is a primitive and we want existing calls to still work so we patch its code body here instead of making a new entry for it )
HERE CLEAR WORD . FIND 4 + @d aHERE !d ] PRINTNUM PUTLN [ -61 ,b aHERE !d
