: WORDCOUNT LATEST 0 BEGIN OVER 0<> WHILE 1 + SWAP @d SWAP REPEAT SWAP POP ;
: STRLEN 0 BEGIN OVER @b 0<> WHILE 1 + SWAP 1 + SWAP REPEAT SWAP POP ;

BYTE_T VARIABLE WHITESPACE 32 WHITESPACE !b
BYTE_T VARIABLE NEWLINE 10 NEWLINE !b
: WORDS 
    LATEST
    BEGIN 
    DUP 0<> WHILE 
        DUP 9 + DUP >C STRLEN >C

        0 0 0 C> C> BASE + 1 1 SYSCALL POP
        0 0 0 1 WHITESPACE BASE + 1 1 SYSCALL POP
        
        @d
    REPEAT
    POP
    0 0 0 1 NEWLINE BASE + 1 1 SYSCALL POP
; 
