: WORDCOUNT LATEST 0 BEGIN OVER WHILE 1 + SWAP @d SWAP REPEAT SWAP POP ;
: STRLEN 0 BEGIN OVER @b WHILE 1 + SWAP 1 + SWAP REPEAT SWAP POP ;

BYTE_T VARIABLE WHITESPACE 32 WHITESPACE !b
BYTE_T VARIABLE NEWLINE 10 NEWLINE !b
: WORDS 
    LATEST
    BEGIN 
    DUP WHILE 
        DUP 9 + DUP >C STRLEN >C

        0 DUP DUP C> C> BASE + 1 DUP SYSCALL POP
        0 DUP DUP 1 WHITESPACE BASE + 1 DUP SYSCALL POP
        
        @d
    REPEAT
    POP
    0 DUP DUP 1 NEWLINE BASE + 1 DUP SYSCALL POP
;
